spring: 

# APLICACAO
  application:
    name: Laço de Amor Servidor

# PERFIL ATIVO
  profiles:
    active: 

# BANCO DE DADOS
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/laco_de_amor
    username: root
    password: root

# LOG
logging:
  level:
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    
# E-MAIL
default:
  sender: lacodeamordf@gmail.com
  recipient: lacodeamordf@gmail.com